### ISSUE TITLE
编译ffmpeg-rk-enc-5.1报错

### ISSUE THREAD

**Issue by catchthebrid** [jjm2473/ffmpeg-rk#12]
![image](https://github.com/jjm2473/ffmpeg-rk/assets/28525883/be1cf377-45d9-409a-84f7-c0f5fcad502f)

下载最新的ffmpeg-rk-enc-5.1进行编译，发现报如上错误

**Comment by catchthebrid** [comment]
已经解决，rga错误

**Comment by climbL** [comment]
> 

请问是怎么解决的

**Comment by catchthebrid** [comment]
> > 
> 
> 请问是怎么解决的

https://github.com/jjm2473/ffmpeg-rk/wiki/%E7%BC%96%E8%AF%91-%7C-Compile

请使用提供的rga

**Comment by climbL** [comment]
> > > 
> > 
> > 
> > 请问是怎么解决的
> 
> https://github.com/jjm2473/ffmpeg-rk/wiki/%E7%BC%96%E8%AF%91-%7C-Compile
> 
> 请使用提供的rga

我试下，感谢！
