### ISSUE TITLE
您好，请教关于h264_rkmpp硬编解码的相关问题

### ISSUE THREAD

**Issue by EZreal-zhangxing** [jjm2473/ffmpeg-rk#17]
您好，我最近在尝试用代码进行h264_rkmpp硬编解码的功能调用，
在rk3588上调用 
`ffmpeg -i /usr/local/test.mp4 -c:v h264_rkmpp -q:v 80 -f matroska -y test.mkv`
能顺利生成。
同时我用ffmpeg 创建了一个h264_rkmpp的解码器，和一个h264_rkmpp的编码器
从文件中读取数据后送入解码器解码，从硬件上得到一个drm的帧
然后将该帧送入编码器中编码后发送到网络上，但是mpp会报如下错误

![image](https://github.com/jjm2473/ffmpeg-rk/assets/8359625/79e08fbb-99a3-4753-9cce-5596a3959f9a)

想请问您一下知道如何解决这个问题吗？

**Comment by 7288Fzq** [comment]
我之前也是报这个错误，直到我 sudo su取得root超级权限后重新执行就没有错误了。仅供你参考
