### ISSUE TITLE
在make时遇到问题

### ISSUE THREAD

**Issue by 7288Fzq** [jjm2473/ffmpeg-rk#19]
blueberry@poodle:~/Downloads/ffmpeg-rk-enc-5.1$ make -j12
GEN	libavutil/libavutil.version
GEN	libswscale/libswscale.version
GEN	libswresample/libswresample.version
GEN	libavcodec/libavcodec.version
GEN	libavformat/libavformat.version
GEN	libavfilter/libavfilter.version
GEN	libavdevice/libavdevice.version
CC	libavdevice/alldevices.o
CC	libavdevice/alsa.o
CC	libavdevice/alsa_enc.o
CC	libavdevice/alsa_dec.o
CC	libavdevice/fbdev_common.o
CC	libavdevice/avdevice.o
CC	libavdevice/fbdev_dec.o
CC	libavdevice/fbdev_enc.o
CC	libavdevice/lavfi.o
CC	libavdevice/oss.o
CC	libavdevice/oss_dec.o
CC	libavdevice/oss_enc.o
CC	libavdevice/timefilter.o
CC	libavdevice/utils.o
CC	libavdevice/v4l2-common.o
CC	libavdevice/v4l2.o
CC	libavdevice/v4l2enc.o
CC	libavdevice/version.o
CC	libavdevice/xcbgrab.o
GEN	libavdevice/libavdevice.pc
CC	libavfilter/aarch64/vf_nlmeans_init.o
AS	libavfilter/aarch64/vf_nlmeans_neon.o
CC	libavfilter/aeval.o
./ffbuild/pkgconfig_generate.sh: 21: .: cannot open libavrkmpp/libavrkmpp.version: No such file
make: *** [ffbuild/library.mak:118: libavdevice/libavdevice.pc] Error 2
make: *** Waiting for unfinished jobs....

**Comment by unjeru** [comment]
the same for OrangePi5 + Ubuntu 22
"fixed" by creating libavrkmpp/libavrkmpp.version (copy of any other) with release 1.0.1, but it's not looks like working way.

**Comment by jjm2473** [comment]
libavrkmpp.version 应该是由脚本生成的

https://github.com/jjm2473/ffmpeg-rk/blob/47ad7b597ec166b560a175a3c4b6663633343546/ffbuild/library.mak#L55 

你看其他lib都没有 .version 文件

**Comment by jjm2473** [comment]
你在执行make之前有执行过configure吗？

例如
`./configure --enable-cross-compile --cross-prefix="aarch64-openwrt-linux-gnu-" --arch="aarch64" --cpu=cortex-a53 --target-os=linux --prefix="/usr" --pkg-config="pkg-config" --enable-shared --enable-static --enable-pthreads --enable-zlib --disable-doc --disable-debug --disable-lzma --disable-vaapi --disable-vdpau --disable-outdevs --disable-runtime-cpudetect --enable-lto --enable-neon --enable-vfp --enable-gnutls  --disable-encoder="svq1"   --enable-libopus --enable-hardcoded-tables --enable-libmp3lame --enable-gpl --enable-libx264 --enable-version3 --enable-nonfree --enable-libdrm --enable-librga --enable-rkmpp  --enable-libfdk-aac`

**Comment by jjm2473** [comment]
不会是连 `--enable-rkmpp` 都没加吧？
