### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Vliro** [jjm2473/ffmpeg-rk#2]
Hi! I have a RK3588 Board(Rock 5B 8GB) running Jellyfin and would gladly like to test/help out with the project.

**Comment by jjm2473** [comment]
check /proc/mpp_service, /dev/rga, /dev/dri or /dev/dma_heap existed on your system, if so MPP should work.

if you have truble with compile FFmpeg, try this docker image first https://hub.docker.com/r/jjm2473/jellyfin-mpp
