### ISSUE TITLE
scale_rga memory leak

### ISSUE THREAD

**Issue by qiuxuewen** [jjm2473/ffmpeg-rk#20]
The **framecontext** is not released.

**vf_scale_rga.c** 
static void rga_release_frame(void *opaque, uint8_t *data)
{
    AVDRMFrameDescriptor *desc = (AVDRMFrameDescriptor *)data;
    RGAFrameContext *framecontext = (RGAFrameContext *)opaque;
    MppBuffer buffer = framecontext->buffer;
    av_free(desc);
    mpp_buffer_put(buffer);
    av_buffer_unref(&framecontext->frame_group_ref);
    **av_free(framecontext);**
}

**Comment by jjm2473** [comment]
Thanks！
