### ISSUE TITLE
Orange Pi 5色彩映射错误

### ISSUE THREAD

**Issue by windskyxb** [jjm2473/ffmpeg-rk#27]
播放HDR10片源时，无论是否开启色彩映射，画面都是灰蒙蒙的
![5ea69f8b9729b138](https://github.com/jjm2473/ffmpeg-rk/assets/60282327/ab16f8e8-350b-4be5-96ff-158abcb3969f)
![69af3edd516b4a30](https://github.com/jjm2473/ffmpeg-rk/assets/60282327/939a1862-1881-414e-b200-eed2a40e5fb0)
这是原片
![image](https://github.com/jjm2473/ffmpeg-rk/assets/60282327/409cd046-31b1-4246-bd2c-ac6c21ae1232)
使用的容器为jjm2473/jellyfin-mpp

**Comment by windskyxb** [comment]
测试过了，只要播放时走转码，无论是硬件解码还是软件界面，均会出现色彩错误的现象；直接播放则不会出现这个问题
![image](https://github.com/jjm2473/ffmpeg-rk/assets/60282327/2c2a1fa4-a898-4e78-be6b-fa2cd472d35d)

**Comment by jjm2473** [comment]
未实现色调映射，而且jellyfin也不能设置任何硬件转码的参数啊，设置以后可能根本没法转码了，因为不是标准的硬件转码框架，是通过warp程序构建mpp转码参数实现的。

**Comment by jjm2473** [comment]
等过段时间看看jellyfin的维护者适配的rk硬解吧。

**Comment by windskyxb** [comment]
> 等过段时间看看jellyfin的维护者适配的rk硬解吧。

预计要多久呢？

**Comment by jjm2473** [comment]
不知道啊，自己去jellyfin那边问下看看
