### ISSUE TITLE
Hevc_rkmpp encode question

### ISSUE THREAD

**Issue by SaltFish001** [jjm2473/ffmpeg-rk#3]
I compiled this project on RK3568(Nano pi R5S), but only has h264_rkmpp encoder.
Is some option error in my ccmds?
`
  ./configure --prefix=/usr --ld="g++"  --enable-nonfree --enable-gpl \
  --enable-version3 --disable-libx264 --disable-libx265 --enable-libmp3lame --enable-libpulse \
  --disable-libv4l2 --enable-libdrm --enable-rkmpp --enable-libxml2 --enable-librtmp --disable-libxvid \
  --enable-libfreetype --enable-openssl --enable-opengl --enable-libopus --enable-libvorbis \
  --enable-shared --enable-static
`

**Comment by jjm2473** [comment]
hevc not implemented

**Comment by jjm2473** [comment]
You can refer h264 encoding implemention and MPP API to implement HEVC encoding.
